cd /d "C:\NewWaveProjetos\jrtercerisados"
echo Removing supabase/.temp from tracking...
git rm -r --cached supabase/.temp/ --quiet
echo Staging all changes...
git add -A
echo Committing...
git commit -m "chore: untrack generated .temp files, commit Sobre fixes" --no-verify
echo Pushing...
git push origin main
echo ALL DONE
