-- 26_error_codes.sql
-- Business error codes for V2.1 SaaS

create type public.business_error_code as enum (
  'INSUFFICIENT_STOCK',
  'DUPLICATE_OPERATION',
  'INVALID_STATUS_TRANSITION',
  'PURCHASE_RECEIPT_ALREADY_CONFIRMED',
  'LGPD_LEGAL_HOLD',
  'UNAUTHORIZED_OPERATION',
  'TENANT_ACCESS_DENIED',
  'CONCURRENT_UPDATE',
  'VALIDATION_ERROR',
  'INTERNAL_ERROR',
  'PAYMENT_ALREADY_PROCESSED',
  'INVOICE_ALREADY_PAID',
  'POS_SESSION_NOT_OPEN',
  'CASH_REGISTER_CLOSED',
  'FISCAL_DOCUMENT_CANCELLED'
);
