-- =============================================================================
-- DATABASE CREATION — JS Empregos SaaS
-- =============================================================================
-- MySQL 8.0 | utf8mb4 | InnoDB
-- Migration target: Supabase PostgreSQL compatible
-- =============================================================================

CREATE DATABASE IF NOT EXISTS js_Empregos
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE js_Empregos;

-- =============================================================================
-- NOTES
-- =============================================================================
-- Charset:   utf8mb4  (4-byte UTF-8, full emoji + international support)
-- Engine:    InnoDB    (ACID, foreign keys, transactions)
-- Collation: utf8mb4_unicode_ci (Unicode 9.0, case-insensitive)
-- =============================================================================
-- Migration to Supabase PostgreSQL:
--   * ENUM → VARCHAR with CHECK constraint
--   * AUTO_INCREMENT → GENERATED BY DEFAULT AS IDENTITY
--   * DATETIME → TIMESTAMP
--   * TINYINT(1) → BOOLEAN
-- =============================================================================
