import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/Button';
import { Section } from '@/components/sections/Section';
import { Container } from '@/components/common/Container';
export default function Cadastro() {
    return (_jsx("div", { className: "min-h-screen", children: _jsx(Section, { className: "pt-24 md:pt-32", children: _jsxs(Container, { children: [_jsxs(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.6 }, className: "mx-auto max-w-2xl text-center", children: [_jsx("h1", { className: "text-foreground text-4xl font-extrabold tracking-tight sm:text-5xl", children: "Comece hoje" }), _jsx("p", { className: "text-muted-foreground mt-4 max-w-lg text-lg", children: "Escolha como deseja se cadastrar na plataforma J&S Empregos." })] }), _jsxs(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { delay: 0.2, duration: 0.6 }, className: "mt-12 grid grid-cols-1 gap-8 md:grid-cols-2", children: [_jsxs(motion.div, { whileHover: { scale: 1.02 }, className: "border-border bg-card rounded-2xl border p-8 text-center", children: [_jsx("h3", { className: "text-foreground mb-2 text-xl font-bold", children: "Sou Candidato" }), _jsx("p", { className: "text-muted-foreground mb-4 text-sm", children: "Cadastre seu curr\u00EDculo e candidate-se \u00E0s vagas." }), _jsx(Link, { to: "/cadastro/candidato", children: _jsx(Button, { variant: "primary", className: "w-full", children: "Cadastrar Curr\u00EDculo" }) })] }), _jsxs(motion.div, { whileHover: { scale: 1.02 }, className: "border-border bg-card rounded-2xl border p-8 text-center", children: [_jsx("h3", { className: "text-foreground mb-2 text-xl font-bold", children: "Sou Empresa" }), _jsx("p", { className: "text-muted-foreground mb-4 text-sm", children: "Publique vagas e encontre os profissionais certos." }), _jsx(Link, { to: "/cadastro/empresa", children: _jsx(Button, { variant: "primary", className: "w-full", children: "Divulgar uma Vaga" }) })] })] })] }) }) }));
}
