import type { CandidatoModuleConfig } from '../types';

export const candidatoSidebarItems: CandidatoModuleConfig[] = [
  {
    id: 'dashboard',
    title: 'Início',
    description: 'Visão geral do seu portal',
    icon: 'Home',
    route: '/candidato',
    requiredPermission: null,
    showInSidebar: true,
    sortOrder: 10,
  },
  {
    id: 'vagas',
    title: 'Vagas',
    description: 'Encontre oportunidades alinhadas ao seu perfil',
    icon: 'Briefcase',
    route: '/candidato/vagas',
    requiredPermission: 'jobs.read',
    showInSidebar: true,
    sortOrder: 20,
  },
  {
    id: 'vagasRecomendadas',
    title: 'Vagas recomendadas',
    description: 'Vagas com alto grau de compatibilidade com seu perfil',
    icon: 'Sparkles',
    route: '/candidato/vagas/recomendadas',
    requiredPermission: 'jobs.read',
    showInSidebar: true,
    sortOrder: 25,
  },
  {
    id: 'buscarVagas',
    title: 'Buscar vagas',
    description: 'Pesquise e filtre vagas',
    icon: 'Search',
    route: '/candidato/buscar-vagas',
    requiredPermission: 'jobs.read',
    showInSidebar: true,
    sortOrder: 30,
  },
  {
    id: 'candidaturas',
    title: 'Minhas Candidaturas',
    description: 'Acompanhe o andamento das suas inscrições',
    icon: 'FileText',
    route: '/candidato/candidaturas',
    requiredPermission: 'applications.read',
    showInSidebar: true,
    sortOrder: 35,
  },
  {
    id: 'entrevistas',
    title: 'Entrevistas',
    description: 'Agendamentos e histórico de entrevistas',
    icon: 'Calendar',
    route: '/candidato/entrevistas',
    requiredPermission: 'applications.read',
    showInSidebar: true,
    sortOrder: 40,
  },
  {
    id: 'historico',
    title: 'Histórico',
    description: 'Histórico de candidaturas finalizadas',
    icon: 'History',
    route: '/candidato/historico',
    requiredPermission: 'applications.read',
    showInSidebar: true,
    sortOrder: 45,
  },
  {
    id: 'favoritas',
    title: 'Vagas Favoritas',
    description: 'Vagas salvas para referência rápida',
    icon: 'Heart',
    route: '/candidato/favoritas',
    requiredPermission: 'jobs.read',
    showInSidebar: true,
    sortOrder: 50,
  },
  {
    id: 'alertas',
    title: 'Alertas de Vagas',
    description: 'Receba notificações de novas oportunidades',
    icon: 'Bell',
    route: '/candidato/alertas',
    requiredPermission: 'candidate_job_alerts.manage',
    showInSidebar: true,
    sortOrder: 55,
  },
  {
    id: 'curriculo',
    title: 'Meu Currículo',
    description: 'Complete seu perfil para mais oportunidades',
    icon: 'FileSignature',
    route: '/candidato/curriculo',
    requiredPermission: 'candidates.self.read',
    showInSidebar: true,
    sortOrder: 60,
  },
  {
    id: 'experiencia',
    title: 'Experiências',
    description: 'Gerencie sua experiência profissional',
    icon: 'Briefcase',
    route: '/candidato/experiencia',
    requiredPermission: 'candidates.self.read',
    showInSidebar: true,
    sortOrder: 65,
  },
  {
    id: 'formacao',
    title: 'Formação',
    description: 'Gerencie sua formação acadêmica',
    icon: 'GraduationCap',
    route: '/candidato/formacao',
    requiredPermission: 'candidates.self.read',
    showInSidebar: true,
    sortOrder: 70,
  },
  {
    id: 'cursos',
    title: 'Cursos',
    description: 'Cursos e capacitações realizados',
    icon: 'Award',
    route: '/candidato/cursos',
    requiredPermission: 'candidates.self.read',
    showInSidebar: true,
    sortOrder: 75,
  },
  {
    id: 'habilidades',
    title: 'Habilidades',
    description: 'Gerencie suas competências técnicas',
    icon: 'Award',
    route: '/candidato/habilidades',
    requiredPermission: 'candidates.self.read',
    showInSidebar: true,
    sortOrder: 80,
  },
  {
    id: 'idiomas',
    title: 'Idiomas',
    description: 'Gerencie seus idiomas',
    icon: 'Languages',
    route: '/candidato/idiomas',
    requiredPermission: 'candidates.self.read',
    showInSidebar: true,
    sortOrder: 85,
  },
  {
    id: 'documentos',
    title: 'Documentos',
    description: 'Documentos e currículo em PDF',
    icon: 'Files',
    route: '/candidato/documentos',
    requiredPermission: 'candidate_documents.read',
    showInSidebar: true,
    sortOrder: 90,
  },
  {
    id: 'preferencias',
    title: 'Preferências',
    description: 'Preferências de vaga e matching',
    icon: 'FileText',
    route: '/candidato/preferencias',
    requiredPermission: 'candidates.self.update',
    showInSidebar: true,
    sortOrder: 95,
  },
  {
    id: 'conta',
    title: 'Minha Conta',
    description: 'Dados pessoais e configurações',
    icon: 'User',
    route: '/candidato/conta',
    requiredPermission: 'account.read',
    showInSidebar: true,
    sortOrder: 100,
  },
  {
    id: 'perfil',
    title: 'Meu Perfil',
    description: 'Dados pessoais e profissionais',
    icon: 'User',
    route: '/candidato/perfil',
    requiredPermission: 'candidates.self.read',
    showInSidebar: true,
    sortOrder: 105,
  },
  {
    id: 'notificacoes',
    title: 'Notificações',
    description: 'Acesse suas notificações e atualizações',
    icon: 'Mail',
    route: '/candidato/notificacoes',
    requiredPermission: 'notifications.read',
    showInSidebar: true,
    sortOrder: 110,
  },
  {
    id: 'configuracoes',
    title: 'Configurações',
    description: 'Gerencie sua conta e preferências',
    icon: 'Settings',
    route: '/candidato/configuracoes',
    requiredPermission: 'account.update',
    showInSidebar: true,
    sortOrder: 120,
  },
];
